// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Infrastructure.Persistences.Database;

#nullable disable

namespace ProvaPub.Infrastructure.Persistences.Migrations
{
    [DbContext(typeof(ProvaPubContext))]
    partial class ProvaPubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("IX_Customers_Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christie Roberts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rafael McClure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nathan Veum"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alfredo Hodkiewicz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jason Legros"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Erick Kshlerin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sylvester Bauch"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Allison McGlynn"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lorraine Mitchell"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jessie Cummerata"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Madeline Steuber"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gilberto Blanda"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Elbert Langworth"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mercedes Schaden"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Milton Conroy"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Myrtle Dickens"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Dan Robel"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gene Goodwin"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Harvey Bernier"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Mae Thiel"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("IX_Orders_Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Orders_CustomerId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("IX_Products_Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_Name");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Licensed Metal Bike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Incredible Cotton Chair"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Awesome Fresh Salad"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Incredible Cotton Soap"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Refined Granite Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantastic Cotton Computer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Licensed Fresh Pizza"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Generic Soft Chair"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Generic Cotton Fish"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Generic Plastic Towels"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Handmade Fresh Pizza"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Unbranded Fresh Hat"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Practical Granite Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Unbranded Steel Pants"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Handcrafted Frozen Chair"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Practical Wooden Keyboard"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Incredible Steel Hat"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Awesome Concrete Fish"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Generic Rubber Mouse"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Licensed Cotton Pants"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Numbers_Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UQ_Numbers_Number");

                    b.ToTable("Numbers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Numbers_Number_Range", "[Number] >= 0 AND [Number] <= 99");
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Order", b =>
                {
                    b.HasOne("ProvaPub.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Customers_Id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
